### ISSUE TITLE
fetch chat

### ISSUE THREAD

**Issue by Luki0193** [0Xiaohei0/LocalAIVtuber#10]
I downloaded the latest release version but I don't see the fetch chat option in the interface.  So I tried to download the entire input-dev code and run it, but in this case I get the error: "ModuleNotFoundError: No module named 'unidecode'". Even though the module is installed, the error still occurs.

**Comment by 0Xiaohei0** [comment]
I updated the requirements.txt, try getting the new version here and run run.bat
https://github.com/0Xiaohei0/LocalAIVtuber/blob/input-dev/requirements.txt
