### ISSUE TITLE
long pauses between sentences

### ISSUE THREAD

**Issue by Luki0193** [0Xiaohei0/LocalAIVtuber#11]
The bot's voice responses take a long time to generate, and after each dot in the sentence there is a long pause, which makes the entire statement sound strange. Is it possible to speed it up or change something in the code so that it generates the entire voice to sentences to be said at once, rather than individual phrases after a dots?

**Comment by 0Xiaohei0** [comment]
you can try removing the highlighted code in LLM.py
![image](https://github.com/0Xiaohei0/LocalAIVtuber/assets/24196833/d34af69a-7cfc-49ac-be12-529c7e6ae032)

**Comment by 0Xiaohei0** [comment]
the long pauses are likely due to tts running on cpu. You can run switch_GPU.bat to speed up generation
