### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio'

### ISSUE THREAD

**Issue by LainAzanael** [0Xiaohei0/LocalAIVtuber#15]
Heeeeeeeeeelp. 

I wanna start this software so badly, but it doesn't start. I get that error:
ModuleNotFoundError: No module named 'gradio'

Please help q   q

Also i get these errors too:

wav2vec2
      running build_ext
      building 'fairseq.libbleu' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
  Building wheel for llama_cpp_python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama_cpp_python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.9.6 using CMake 3.29.5 (wheel)
      *** Configuring CMake...
      2024-06-16 09:26:15,379 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\Omistaja\Downloads\LocalAIVtuber-0.1.1\installer_files\tmpqug5_pq6\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama_cpp_python
  Building wheel for simpleaudio (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\simpleaudio
      copying simpleaudio\__init__.py -> build\lib.win-amd64-cpython-310\simpleaudio
      copying simpleaudio\shiny.py -> build\lib.win-amd64-cpython-310\simpleaudio
      copying simpleaudio\functionchecks.py -> build\lib.win-amd64-cpython-310\simpleaudio
      creating build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      copying simpleaudio\test_audio\c.wav -> build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      copying simpleaudio\test_audio\e.wav -> build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      copying simpleaudio\test_audio\g.wav -> build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      copying simpleaudio\test_audio\left_right.wav -> build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      copying simpleaudio\test_audio\notes_2_16_44.wav -> build\lib.win-amd64-cpython-310\simpleaudio\test_audio
      running build_ext
      building 'simpleaudio._simpleaudio' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simpleaudio
  Running setup.py clean for simpleaudio
Failed to build fairseq llama_cpp_python simpleaudio
ERROR: Could not build wheels for fairseq, llama_cpp_python, simpleaudio, which is required to install pyproject.toml-based projects
Collecting torch

**Comment by 0Xiaohei0** [comment]
Seems like you don't have Microsoft C++ Build Tools installed. Are you using run.bat? it should install the build tool automatically for you.

**Comment by LainAzanael** [comment]
i was using run.bat. it wasn t installing c++ apparently. i deleted the folder, went to visual studio and manually installed the c++ package. i retried using the bat in a new fresh unzipped folder. it works now. thanks.
