### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by ScottAust1n** [0Xiaohei0/LocalAIVtuber#16]
How can I fix this issue?
http://localhost:7860  won't open on my browser
![1pCbmbT](https://github.com/user-attachments/assets/a8311f35-ff47-463e-8255-96cff73a1c44)

**Comment by 0Xiaohei0** [comment]
please send full console log

**Comment by 0Xiaohei0** [comment]
I made an zip file containing the entire project with everything installed, you can download it here:
https://huggingface.co/xiaoheiqaq/LocalAiVtuber-windows-package/resolve/main/LocalAIVtuber.zip?download=true

**Comment by ScottAust1n** [comment]
I really appreciate this you have no Idea but sadly it's still not working here I took a video

https://github.com/user-attachments/assets/427f4d4d-c48e-4467-8592-20b82559f006

**Comment by 0Xiaohei0** [comment]
The error says the path cannot contain spaces, I see that you saved this under a folder named "Ai Vtuber 2" which contains spaces. Try renaming "Ai Vtuber 2" to "AiVtuber2"

**Comment by ScottAust1n** [comment]
![OIP (85)](https://github.com/user-attachments/assets/331221ca-6a02-4940-a5c1-87d7b639b176)

**Comment by ScottAust1n** [comment]
Ok now how do I get it to read twitch chat
![OIP (85)](https://github.com/user-attachments/assets/b5f03b46-afc6-43f2-b6f0-169829bbe59f)

**Comment by 0Xiaohei0** [comment]
This version only has youtube chat

**Comment by ScottAust1n** [comment]
![OIP (85)](https://github.com/user-attachments/assets/2223f19b-4697-4fff-9968-5baa91bbc92e)
Is there a way i can implement it myself?

**Comment by 0Xiaohei0** [comment]
I already implemented here https://github.com/0Xiaohei0/LocalAIVtuber/tree/input-dev/plugins/TwitchChatFetch
will be in the zip when next version come out.

**Comment by ScottAust1n** [comment]
![OIP (85)](https://github.com/user-attachments/assets/a5fa98bc-fc99-403a-8cdb-7d805bdef17d)
Is there a way for the AI to process faster so it can talk?

**Comment by ScottAust1n** [comment]
How can I upgrade my AI and make it more aware?

**Comment by ScottAust1n** [comment]
help me please

**Comment by goenyan** [comment]
> Is there a way for the AI to process faster so it can talk? ![vbnnhbn](https://private-user-images.githubusercontent.com/117759879/358876831-72bb7fcb-21ab-4c55-8e25-b11a1308c815.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDM3MzgsIm5iZiI6MTcyNjU0MzQzOCwicGF0aCI6Ii8xMTc3NTk4NzkvMzU4ODc2ODMxLTcyYmI3ZmNiLTIxYWItNGM1NS04ZTI1LWIxMWExMzA4YzgxNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwMzIzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDQzMzY5ZTMwYzE1MTQxY2NkYzM2MDJiOGYwZTRkMzBlMzM4YWZiNjZkMWMxZGYxOWJiNDJjZWQyMmFlN2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nzm0PedXYXuwahk5ydb6tNvHn1ci-2QJaEuSeIcBTww)

This is entirely dependent on your PC's processing speed. If you want faster performance, upgrade to a higher-spec PC.



> can you please give me a response this is ridiculous its been a month

You're the one being ridiculous. The author has no responsibility to support you, you're literally using the software for free, so don't expect immediate assistance.

**Comment by 0Xiaohei0** [comment]
> Is there a way for the AI to process faster so it can talk? ![vbnnhbn](https://private-user-images.githubusercontent.com/117759879/358876831-72bb7fcb-21ab-4c55-8e25-b11a1308c815.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4NjAzMTYsIm5iZiI6MTcyNjg2MDAxNiwicGF0aCI6Ii8xMTc3NTk4NzkvMzU4ODc2ODMxLTcyYmI3ZmNiLTIxYWItNGM1NS04ZTI1LWIxMWExMzA4YzgxNS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQxOTIwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2YyODA5MTA0Y2Q4N2ZmNDk5OWQ2YjkwYTA4NjNjMThlOTlmYjMyMzBhZmNlMzIyZTVmNTQxZTMyZjUxM2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e8R0Fz4-FeRiT5OOrtaQ8PNhs8JNCu-1V5tpwmesVOs)

It shouldn't be taking this long even if you are running on cpu. please send full console output. It's most likely just downloading the model file.



> How can I upgrade my AI and make it more aware?
I'm working on finetuning a better local model to make it seem more aware.
for now, you can try adjusting the system prompt.
