### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Khaliostra** [0Xiaohei0/LocalAIVtuber#17]
I'm sorry, I'm not a code guru, but what to do when launching a bat file, an error appears

WARNING: Ignoring version 2.0.6 of omegaconf since it has invalid metadata:
Requested omegaconf==2.0.6 from https://files.pythonhosted.org/packages/d0/eb/9d63ce09dd8aa85767c65668d5414958ea29648a0eec80a4a7d311ec2684/omegaconf-2.0.6-py3-none-any.whl (from -r requirements.txt (line 74)) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    PyYAML (>=5.1.*)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Ignored the following yanked versions: 1.0.0, 1.0.1, 1.0.2, 2.0.0rc1, 2.0.0rc2, 2.0.0rc22, 2.0.0rc23, 2.0.0rc24, 2.0.0rc25, 2.0.0rc26, 2.0.0rc27, 2.0.0rc28, 2.0.0rc29, 2.0.1rc1, 2.0.1rc2, 2.0.1rc3, 2.0.1rc4, 2.0.1rc5, 2.2.0
ERROR: Ignored the following versions that require a different python version: 0.36.0 Requires-Python >=3.6,<3.10; 0.37.0 Requires-Python >=3.7,<3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement omegaconf==2.0.6 (from versions: 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.16, 1.0.17, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.2.0, 1.2.1, 1.3.0rc1, 1.3.0rc2, 1.3.0rc3, 1.3.0rc4, 1.3.0rc5, 1.3.0rc6, 1.3.0rc7, 1.3.0rc8, 1.3.0rc9, 1.3.0rc10, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0rc4, 1.4.0, 1.4.1rc1, 1.4.1, 2.0.0rc3, 2.0.0rc4, 2.0.0rc5, 2.0.0rc6, 2.0.0rc7, 2.0.0rc8, 2.0.0rc9, 2.0.0rc10, 2.0.0rc11, 2.0.0rc12, 2.0.0rc13, 2.0.0rc14, 2.0.0rc15, 2.0.0rc16, 2.0.0rc17, 2.0.0rc18, 2.0.0rc19, 2.0.0rc20, 2.0.0rc21, 2.0.0, 2.0.1rc6, 2.0.1rc7, 2.0.1rc8, 2.0.1rc9, 2.0.1rc10, 2.0.1rc11, 2.0.1rc12, 2.0.1rc13, 2.0.1, 2.0.2rc1, 2.0.2rc2, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0.dev1, 2.1.0.dev2, 2.1.0.dev3, 2.1.0.dev4, 2.1.0.dev5, 2.1.0.dev6, 2.1.0.dev7, 2.1.0.dev8, 2.1.0.dev9, 2.1.0.dev10, 2.1.0.dev11, 2.1.0.dev12, 2.1.0.dev13, 2.1.0.dev14, 2.1.0.dev15, 2.1.0.dev16, 2.1.0.dev17, 2.1.0.dev18, 2.1.0.dev19, 2.1.0.dev20, 2.1.0.dev21, 2.1.0.dev22, 2.1.0.dev23, 2.1.0.dev24, 2.1.0.dev25, 2.1.0.dev26, 2.1.0.dev27, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0.dev1, 2.2.0.dev2, 2.2.0.dev3, 2.2.0.dev4, 2.2.0.dev5, 2.2.1, 2.2.2, 2.2.3, 2.3.0.dev0, 2.3.0.dev1, 2.3.0.dev2, 2.3.0, 2.4.0.dev0, 2.4.0.dev1, 2.4.0.dev2, 2.4.0.dev3)
ERROR: No matching distribution found for omegaconf==2.0.6
Requirement already satisfied: torch in c:\localaivtuber\installer_files\env\lib\site-packages (2.4.0)
Requirement already satisfied: torchaudio in c:\localaivtuber\installer_files\env\lib\site-packages (2.4.0)
Requirement already satisfied: filelock in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (1.13.2)
Requirement already satisfied: networkx in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\localaivtuber\installer_files\env\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\localaivtuber\installer_files\env\lib\site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\localaivtuber\installer_files\env\lib\site-packages (from sympy->torch) (1.3.0)
Starting main.py...
Traceback (most recent call last):
  File "C:\LocalAIVtuber\main.py", line 2, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Для продолжения нажмите любую клавишу . . .

**Comment by 0Xiaohei0** [comment]
I updated run.bat to use an older pip version, you can try replacing run.bat and run it again
https://github.com/0Xiaohei0/LocalAIVtuber/blob/master/run.bat

**Comment by Khaliostra** [comment]
Please can you still help



Extracting ffmpeg-release-essentials.zip...
Traceback (most recent call last):
  File "C:\AIVtuber\main.py", line 28, in <module>
    tts = TTS()
  File "C:\AIVtuber\TTS.py", line 37, in __init__
    self.check_ffmpeg()
  File "C:\AIVtuber\TTS.py", line 215, in check_ffmpeg
    with zipfile.ZipFile(file_name, 'r') as zip_ref:
  File "C:\AIVtuber\installer_files\env\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "C:\AIVtuber\installer_files\env\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Для продолжения нажмите любую клавишу . . .

**Comment by 0Xiaohei0** [comment]
I made an zip file containing the entire project with everything installed, you can download it here:
https://huggingface.co/xiaoheiqaq/LocalAiVtuber-windows-package/resolve/main/LocalAIVtuber.zip?download=true

**Comment by 0Xiaohei0** [comment]
https://github.com/0Xiaohei0/LocalAIVtuber/blob/master/plugins/gpt_sovits/GPT_SoVITS/api_direct.py#L67

Change this line to just device = "cuda"

**Comment by Zimigames** [comment]
okay that fixed that error but now its looking for a file 'E:\\LocalAIVtuber-master\\plugins\\gpt_sovits\\models\\leaf\\leaf_e8_s136.pth'

i cant find it online anywhere, that leaf_e9_s136.pth

**Comment by 0Xiaohei0** [comment]
There is now a tutorial video on how to set up everything: https://youtu.be/Yl-T3YgePmw?si=n-vaZzClw0Q833E5
The leaf_e8_s136.pth file among other models files are included in the new zip file in releases section https://github.com/0Xiaohei0/LocalAIVtuber/releases/download/v0.2.0/LAV_v0.2.zip

You can download the zip file and follow the tutorial from there.

**Comment by xsploit** [comment]
torch.cuda.is_available() True
refer_wav_path C:\Users\SUBSECT\Downloads\LAV_v0.2\LAV_v0.2\plugins\gpt_sovits\models\leaf\The birch canoe slid on the smooth planks..wav
prompt_text The birch canoe slid on the smooth planks.Glue the sheet to the dark blue background.
prompt_language en
Failed to generate audio file.
**********************************************************************
  Resource averaged_perceptron_tagger_eng not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger_eng')

  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger_eng/

  Searched in:
    - 'C:\\Users\\SUBSECT/nltk_data'
    - 'C:\\Users\\SUBSECT\\Downloads\\LAV_v0.2\\LAV_v0.2\\venv\\nltk_data'
    - 'C:\\Users\\SUBSECT\\Downloads\\LAV_v0.2\\LAV_v0.2\\venv\\share\\nltk_data'
    - 'C:\\Users\\SUBSECT\\Downloads\\LAV_v0.2\\LAV_v0.2\\venv\\lib\\nltk_data'
    - 'C:\\Users\\SUBSECT\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

Exception in thread Thread-132 (generate_audio):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\SUBSECT\Downloads\LAV_v0.2\LAV_v0.2\TTS.py", line 100, in generate_audio
    self.audio_data_queue.put([function(input), input])
  File "C:\Users\SUBSECT\Downloads\LAV_v0.2\LAV_v0.2\plugins\gpt_sovits\gptSovits.py", line 63, in synthesize
    return response
UnboundLocalError: local variable 'response' referenced before assignment

**Comment by 0Xiaohei0** [comment]
open new command prompt
pip install nltk
python -m nltk.downloader -d C:\nltk_data all
