### ISSUE TITLE
i dont understand this bcs i already install torch also

### ISSUE THREAD

**Issue by DukeLuke1** [0Xiaohei0/LocalAIVtuber#18]
C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\Aya_LLM_GGUF checking: C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\Chess checking: C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\gpt_sovits checking: C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\Idle_think checking: C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\Local_EN_to_JA Traceback (most recent call last): File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\main.py", line 23, in <module> plugin_loader.load_plugins() File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\pluginLoader.py", line 50, in load_plugins self._load_plugins_from_directory(item_path) File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\pluginLoader.py", line 68, in load_plugins_from_directory spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in call_with_frames_removed File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\plugins\Local_EN_to_JA\Local_EN_to_JA.py", line 3, in <module> from transformers import MarianMTModel, MarianTokenizer File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\transformers_init.py", line 26, in <module> from . import dependency_versions_check File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module> from .utils.versions import require_version, require_version_core File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\transformers\utils_init.py", line 33, in <module> from .generic import ( File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\transformers\utils\generic.py", line 465, in <module> import torch.utils._pytree as torch_pytree File "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\torch_init.py", line 148, in <module> raise err OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\story\Downloads\LocalAIVtuber\LocalAIVtuber\installer_files\env\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by DukeLuke1** [comment]
also i wanna ask can i use this ai in linux ubuntu ?

**Comment by 0Xiaohei0** [comment]
Try with the new installation instructions, the integrated package doesn't seem to work on all machines. You can make this work on linux, but there are some windows specific path name and functions you need to debug and change.
