### ISSUE TITLE
Is there any way to retrain?

### ISSUE THREAD

**Issue by usagi-code** [0Xiaohei0/LocalAIVtuber#19]
I would love to use it but it just wont shut up about chess

**Comment by 0Xiaohei0** [comment]
Have you tried changing the system prompt? It's under additional inputs. 
Also I trained an improved version here: https://huggingface.co/xiaoheiqaq/Aya-v0.2-Q4_K_M-GGUF

**Comment by usagi-code** [comment]
ok so i tossed in the new model and she immediately started rambling on about playing chess. Is there a way to fine-tune a model so she's not stuck on playing chess? I honestly wouldn't mind removing it from her vocab entirely.

**Comment by usagi-code** [comment]
nope still set on chess

**Comment by 0Xiaohei0** [comment]
![image](https://github.com/user-attachments/assets/461510f6-f7a1-4cde-ad67-2eb100eb5900)
there is this additional input dropdown, where you can set the system prompt.

**Comment by 0Xiaohei0** [comment]
https://github.com/0Xiaohei0/LocalAIVtuber/issues/32#issuecomment-2468915767
