### ISSUE TITLE
ModuleNotFoundError: No module named 'rvc'

### ISSUE THREAD

**Issue by VinRuan99** [0Xiaohei0/LocalAIVtuber#2]
i ran the run.bat file and during the installation of the libraries i got this error
![image](https://github.com/0Xiaohei0/LocalAIVtuber/assets/102473309/c2e57c09-5108-46f7-9a9a-e4d1854fe7d2)

**Comment by BasedAnon** [comment]
SAME!

**Comment by BasedAnon** [comment]
I tried working with it, but it's in Dependency Hell.

**Comment by 0Xiaohei0** [comment]
I pushed some fixes to main, the setup script should work now, let me know if there are still errors.

**Comment by VihRuan** [comment]
I tried again and it still had that error :'(
ModuleNotFoundError: No module named 'rvc'

**Comment by 0Xiaohei0** [comment]
You can try delete the plugin/rvc folder

**Comment by BasedAnon** [comment]
> You can try delete the plugin/rvc folder

I tried this, and now it's running!  Thanks!
