### ISSUE TITLE
Changing RVC pitch extraction method?

### ISSUE THREAD

**Issue by chips17A** [0Xiaohei0/LocalAIVtuber#20]
I was wondering if its possible to change the pitch extraction method for RVC to PM?
I do not have the best computer, but I hear PM is the fastest if I remember correctly.
I don't mind if the output with PM is low quality, I just want RVC to infer faster...

Thanks!

**Comment by 0Xiaohei0** [comment]
For RVC to infer faster, make sure you are running it on the gpu. There is a script for changing pytorch to the gpu version: https://github.com/0Xiaohei0/LocalAIVtuber/blob/master/switch_GPU.bat
