### ISSUE TITLE
cant connect to vtube studio api

### ISSUE THREAD

**Issue by nekohacker591** [0Xiaohei0/LocalAIVtuber#24]
Received message: {"apiName":"VTubeStudioPublicAPI","apiVersion":"1.0","timestamp":1728144856993,"messageType":"APIError","requestID":"2","data":{"errorID":8,"message":"Current session is not authenticated. The only requests you can send without authenticating are: [APIStateRequest, AuthenticationTokenRequest, AuthenticationRequest]"}}

**Comment by 0Xiaohei0** [comment]
You can delete plugins\VtubeStudio\token.txt
and press authenticate again, there should be a pop up in vtube studio you need to accept. Once accepted, it should generate a new token file.

Once connected, you need to set the Mouth Open input to MouthOpen, this will allow you to send the audio to vtube studio without a virtual audio cable:
![image](https://github.com/user-attachments/assets/f08fc9b7-c5b8-4ba3-8ac0-4af951c680b1)
