### ISSUE TITLE
Issue with installing llama-cpp-python

### ISSUE THREAD

**Issue by pythontor** [0Xiaohei0/LocalAIVtuber#25]
While installing llama-cpp-python using pip 21.2.3 I faced several problems. First one is this:

     -- Could NOT find Git (missing: GIT_EXECUTABLE)
  CMake Warning at vendor/llama.cpp/cmake/build-info.cmake:14 (message):
    Git not found.  Build info will not be accurate.
  Call Stack (most recent call first):
    vendor/llama.cpp/CMakeLists.txt:77 (include)

  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
    

And the next one here:

  -- CUDA found
  -- Using CUDA architectures: 52;61;70;75
  CMake Error at C:/Users/miha/AppData/Local/Temp/pip-build-env-8cka806p/normal/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:587 (message):
    No CUDA toolset found.
  Call Stack (most recent call first):
    C:/Users/miha/AppData/Local/Temp/pip-build-env-8cka806p/normal/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
    C:/Users/miha/AppData/Local/Temp/pip-build-env-8cka806p/normal/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
    C:/Users/miha/AppData/Local/Temp/pip-build-env-8cka806p/normal/Lib/site-packages/cmake/data/share/cmake-3.30/Modules/CMakeDetermineCUDACompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID)
    vendor/llama.cpp/ggml/src/CMakeLists.txt:299 (enable_language)

  -- Configuring incomplete, errors occurred!

  *** CMake configuration failed
  Building wheel for llama-cpp-python (PEP 517) ... error
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.2.3; however, version 24.2 is available.
You should consider upgrading via the 'C:\AIVtube\LAV_v0.2\venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by 0Xiaohei0** [comment]
You can try running the command prompt as administrator.
Also you can install the cpu version of llama-cpp-python by just running
```
pip install llama-cpp-python
```
This will be a lot faster to install and will only slightly increase latency
