### ISSUE TITLE
TTS volume stucked on 1% on Windows 11

### ISSUE THREAD

**Issue by TrueAlexFisher** [0Xiaohei0/LocalAIVtuber#31]
![Untitled](https://github.com/user-attachments/assets/006403e6-41fc-40bc-90fe-f12bfef43489)
I am unable to hear bot's voice because the TTS output volume is somehow stucked on 1%. It is impossible to increase the volume of the app via Windows 11. System restart, drivers update and other regular solutions did not work. Currently this is the first time I encountered this issue, any other Python program and any app work on my system with no sound issues.

Could you please advise on this problem?

**Comment by Lumierezx** [comment]
did you find a solution ?
