### ISSUE TITLE
Error: This script relies on Miniconda which can not be silently installed

### ISSUE THREAD

**Issue by Adventurinee** [0Xiaohei0/LocalAIVtuber#5]
I ran the run.bat and this is what came up what do I do?
![5535](https://github.com/0Xiaohei0/LocalAIVtuber/assets/165175269/a8f1fbca-1ca8-4667-bdc8-34d0b96e7e52)

**Comment by 0Xiaohei0** [comment]
does the path to the program include spaces?

**Comment by Adventurinee** [comment]
yes for some reason it keeps creating a folder with spaces (Rar$DIa29536.41496)
![5535](https://github.com/0Xiaohei0/LocalAIVtuber/assets/165175269/8d3db039-3b94-4a89-96bf-c81a9d3b8db6)

**Comment by Adventurinee** [comment]
Any ideas?
![5535](https://github.com/0Xiaohei0/LocalAIVtuber/assets/165175269/1c79a93f-fb88-4641-b74a-12c99f92270f)

**Comment by 0Xiaohei0** [comment]
"Ai Vtuber 2" contains spaces

**Comment by Adventurinee** [comment]
What do I do now?
![IMG-1182](https://github.com/0Xiaohei0/LocalAIVtuber/assets/165175269/ddbde128-c8f1-4266-97e4-5242d6d68c69)

**Comment by 0Xiaohei0** [comment]
It's running now, just go to http://127.0.0.1:7860 on your browser

**Comment by Adventurinee** [comment]
And to add my twitch ID I can't switch it from youtube
![Adffsdfgdf](https://github.com/0Xiaohei0/LocalAIVtuber/assets/165175269/7970876f-cdb3-4bc6-ba75-9266e3b3cf2a)

**Comment by 0Xiaohei0** [comment]
twitch is not yet implemented
