### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==2.2.1+cu118

### ISSUE THREAD

**Issue by Tremer19** [0Xiaohei0/LocalAIVtuber#7]
Now im using Python3.8.0 but the error is still there. (already tried 3.9 and 3.10)
My CUDA Version is: 12.4

![capture](https://github.com/0Xiaohei0/LocalAIVtuber/assets/162058069/07d2a13c-975e-4a54-aae5-5eaf79717eac)

**Comment by 0Xiaohei0** [comment]
Should be fixed now, try downloading the zip from releases https://github.com/0Xiaohei0/LocalAIVtuber/releases
