### ISSUE TITLE
adjust TTS.py for macos

### ISSUE THREAD

**Issue by netixc** [0Xiaohei0/LocalAIVtuber#9]
Can u Adjust TTS.py for macos please the current setup is with .exe for windows

ive tried to do it myself but it alsways keeps downloading the zip with the .exe

**Comment by 0Xiaohei0** [comment]
try removing this line here and install ffmpeg manually if needed:
![image](https://github.com/0Xiaohei0/LocalAIVtuber/assets/24196833/8ac51cd2-ae5c-44df-bbc1-ba90f4922c98)
